name: Databricks Deployment

on:
  push:
    branches:
      - Dev
      - main

jobs:
  deploy-Dev:
    if: github.ref == 'refs/heads/Dev'
    runs-on: self-hosted

    env:
      DATABRICKS_HOST: "https://adb-2990609490919825.5.azuredatabricks.net/"
      DATABRICKS_TOKEN: "dapi121fb6bd3b99b53941513362eb45ec3b-3"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set PowerShell execution policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: pwsh
        
      - name: Unblock PowerShell scripts
        run: Get-ChildItem -Path . -Recurse -Filter *.ps1 | Unblock-File
        shell: pwsh

      - name: Install Databricks CLI
        run: echo "Hello World"

  # deploy-prod:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest

  #   env:
  #     DATABRICKS_HOST: "https://adb-1444941199492748.8.azuredatabricks.net/"
  #     DATABRICKS_TOKEN: "dapi9a2a4f9a9dfd07aa1503896d2c18bf6b-3"

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install Databricks CLI
  #       run: |
  #         echo "Hello World"
